/* ============================================================
   BATCHES DATA — 2 Batches, 4 Students
   No avatar: students provide their own photo on profile setup.
============================================================ */

export const batches = [
  {
    id: "b1",
    name: "Batch A",
    grade: "Grade 10",
    subject: "Mathematics",
    totalStudents: 2,
    schedule: "Mon, Wed, Fri · 9:00 AM",
    color: "blue",
  },
  {
    id: "b2",
    name: "Batch C",
    grade: "Grade 9",
    subject: "Science",
    totalStudents: 2,
    schedule: "Tue, Thu · 11:00 AM",
    color: "green",
  },
];

export const students = [
  /* ── Batch A — Mathematics, Grade 10 ── */
  {
    id: "s01",
    batchId: "b1",
    name: "Priya Sharma",
    rollNo: "A-01",
    grade: "Grade 10",
    avatar: null,           // No photo yet — placeholder will show initials
    email: "priya.sharma@student.com",
    phone: "+91 98765 00003",
    parent: "Mr. Raj Sharma",
    parentPhone: "+91 98765 10003",
    joinedOn: "Jun 2025",
    attendancePercent: 100,
    avgScore: 95,
    rank: 1,
    status: "active",
    attendance: [
      { week: "Week 1 (Jul 1–5)",   present: 3, total: 3, classes: ["Mon (P)", "Wed (P)", "Fri (P)"] },
      { week: "Week 2 (Jul 8–12)",  present: 3, total: 3, classes: ["Mon (P)", "Wed (P)", "Fri (P)"] },
      { week: "Week 3 (Jul 15–19)", present: 3, total: 3, classes: ["Mon (P)", "Wed (P)", "Fri (P)"] },
      { week: "Week 4 (Jul 22–26)", present: 3, total: 3, classes: ["Mon (P)", "Wed (P)", "Fri (P)"] },
    ],
    assignments: [
      { title: "Chapter 3 Worksheet",  submitted: "Jul 4",  score: 20, maxScore: 20, status: "reviewed"  },
      { title: "Algebra Practice Set", submitted: "Jul 11", score: 25, maxScore: 25, status: "reviewed"  },
      { title: "Chapter 5 Worksheet",  submitted: "Jul 18", score: 19, maxScore: 20, status: "reviewed"  },
      { title: "Geometry Problems",    submitted: "Jul 24", score: null, maxScore: 20, status: "submitted" },
    ],
    tests: [
      { title: "Weekly Test 1", date: "Jul 4",  score: 48, maxScore: 50, grade: "A+" },
      { title: "Weekly Test 2", date: "Jul 11", score: 47, maxScore: 50, grade: "A+" },
      { title: "Weekly Test 3", date: "Jul 18", score: 49, maxScore: 50, grade: "A+" },
      { title: "Weekly Test 4", date: "Jul 25", score: 50, maxScore: 50, grade: "A+" },
    ],
  },
  {
    id: "s02",
    batchId: "b1",
    name: "Aryan Patel",
    rollNo: "A-02",
    grade: "Grade 10",
    avatar: null,
    email: "aryan.patel@student.com",
    phone: "+91 98765 00004",
    parent: "Mrs. Meena Patel",
    parentPhone: "+91 98765 10004",
    joinedOn: "Jun 2025",
    attendancePercent: 78,
    avgScore: 68,
    rank: 2,
    status: "active",
    attendance: [
      { week: "Week 1 (Jul 1–5)",   present: 2, total: 3, classes: ["Mon (P)", "Wed (A)", "Fri (P)"] },
      { week: "Week 2 (Jul 8–12)",  present: 2, total: 3, classes: ["Mon (P)", "Wed (P)", "Fri (A)"] },
      { week: "Week 3 (Jul 15–19)", present: 1, total: 3, classes: ["Mon (A)", "Wed (A)", "Fri (P)"] },
      { week: "Week 4 (Jul 22–26)", present: 2, total: 3, classes: ["Mon (P)", "Wed (P)", "Fri (A)"] },
    ],
    assignments: [
      { title: "Chapter 3 Worksheet",  submitted: "Jul 7",  score: 12, maxScore: 20, status: "reviewed" },
      { title: "Algebra Practice Set", submitted: "Jul 15", score: 16, maxScore: 25, status: "reviewed" },
      { title: "Chapter 5 Worksheet",  submitted: null,     score: null, maxScore: 20, status: "missing"  },
      { title: "Geometry Problems",    submitted: "Jul 26", score: null, maxScore: 20, status: "submitted" },
    ],
    tests: [
      { title: "Weekly Test 1", date: "Jul 4",  score: 28, maxScore: 50, grade: "C"  },
      { title: "Weekly Test 2", date: "Jul 11", score: 32, maxScore: 50, grade: "C+" },
      { title: "Weekly Test 3", date: "Jul 18", score: 35, maxScore: 50, grade: "B-" },
      { title: "Weekly Test 4", date: "Jul 25", score: 33, maxScore: 50, grade: "C+" },
    ],
  },

  /* ── Batch C — Science, Grade 9 ── */
  {
    id: "s03",
    batchId: "b2",
    name: "Rohan Gupta",
    rollNo: "C-01",
    grade: "Grade 9",
    avatar: null,
    email: "rohan.gupta@student.com",
    phone: "+91 98765 00010",
    parent: "Mr. Suresh Gupta",
    parentPhone: "+91 98765 10010",
    joinedOn: "Jun 2025",
    attendancePercent: 100,
    avgScore: 92,
    rank: 1,
    status: "active",
    attendance: [
      { week: "Week 1 (Jul 1–5)",   present: 2, total: 2, classes: ["Tue (P)", "Thu (P)"] },
      { week: "Week 2 (Jul 8–12)",  present: 2, total: 2, classes: ["Tue (P)", "Thu (P)"] },
      { week: "Week 3 (Jul 15–19)", present: 2, total: 2, classes: ["Tue (P)", "Thu (P)"] },
      { week: "Week 4 (Jul 22–26)", present: 2, total: 2, classes: ["Tue (P)", "Thu (P)"] },
    ],
    assignments: [
      { title: "Lab Report 1",       submitted: "Jul 5",  score: 20, maxScore: 20, status: "reviewed" },
      { title: "Chapter 4 Notes",    submitted: "Jul 12", score: 24, maxScore: 25, status: "reviewed" },
      { title: "Physics Assignment", submitted: "Jul 20", score: 19, maxScore: 20, status: "reviewed" },
    ],
    tests: [
      { title: "Weekly Test 1", date: "Jul 5",  score: 46, maxScore: 50, grade: "A+" },
      { title: "Weekly Test 2", date: "Jul 12", score: 47, maxScore: 50, grade: "A+" },
      { title: "Weekly Test 3", date: "Jul 19", score: 48, maxScore: 50, grade: "A+" },
      { title: "Weekly Test 4", date: "Jul 26", score: 45, maxScore: 50, grade: "A"  },
    ],
  },
  {
    id: "s04",
    batchId: "b2",
    name: "Kavya Reddy",
    rollNo: "C-02",
    grade: "Grade 9",
    avatar: null,
    email: "kavya.reddy@student.com",
    phone: "+91 98765 00011",
    parent: "Mr. Srinivas Reddy",
    parentPhone: "+91 98765 10011",
    joinedOn: "Jun 2025",
    attendancePercent: 75,
    avgScore: 63,
    rank: 2,
    status: "active",
    attendance: [
      { week: "Week 1 (Jul 1–5)",   present: 1, total: 2, classes: ["Tue (A)", "Thu (P)"] },
      { week: "Week 2 (Jul 8–12)",  present: 2, total: 2, classes: ["Tue (P)", "Thu (P)"] },
      { week: "Week 3 (Jul 15–19)", present: 1, total: 2, classes: ["Tue (P)", "Thu (A)"] },
      { week: "Week 4 (Jul 22–26)", present: 2, total: 2, classes: ["Tue (P)", "Thu (P)"] },
    ],
    assignments: [
      { title: "Lab Report 1",       submitted: "Jul 8",  score: 13, maxScore: 20, status: "reviewed" },
      { title: "Chapter 4 Notes",    submitted: "Jul 16", score: 16, maxScore: 25, status: "reviewed" },
      { title: "Physics Assignment", submitted: null,     score: null, maxScore: 20, status: "missing"  },
    ],
    tests: [
      { title: "Weekly Test 1", date: "Jul 5",  score: 28, maxScore: 50, grade: "C"  },
      { title: "Weekly Test 2", date: "Jul 12", score: 30, maxScore: 50, grade: "C+" },
      { title: "Weekly Test 3", date: "Jul 19", score: 33, maxScore: 50, grade: "C+" },
      { title: "Weekly Test 4", date: "Jul 26", score: 36, maxScore: 50, grade: "B-" },
    ],
  },
];
